### ISSUE TITLE
NoMethodError (undefined method `author_id=' for #<KbArticle:0x34e8430>):

### ISSUE THREAD

**Issue by andreydruz** [alexbevi/redmine_knowledgebase#272]
If I trying to create article I get

```
Started POST "/projects/uco-cms/knowledgebase/articles" for 79.179.146.110 at 2015-02-20 21:52:07 +0200
Processing by ArticlesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"uuyySpuKhc+av/A8EeBxr+1drollmVrjKv8OnFnwWkI=", "category_id"=>"1", "article"=>{"title"=>"fhdfh fdhdfhdfh", "summary"=>"gdhfh", "content"=>"fdhdfghfgh", "tag_list"=>"dfhfh", "version_comments"=>"gghfhfgh"}, "commit"=>"Create", "project_id"=>"uco-cms"}
  [1m[36m (0.0ms)[0m  [1mEXEC sp_executesql N'SELECT MAX([settings].[updated_on]) AS max_id FROM [settings]'[0m
  [1m[35mUser Load (0.0ms)[0m  EXEC sp_executesql N'SELECT TOP (1) [users].* FROM [users] WHERE [users].[type] IN (N''User'', N''AnonymousUser'') AND [users].[status] = 1 AND [users].[id] = @0', N'@0 int', @0 = 10  [["id", 10]]
  Current user: andrey (id=10)
  [1m[36m (0.0ms)[0m  [1mEXEC sp_executesql N'SELECT MAX([contacts_settings].[updated_on]) AS max_id FROM [contacts_settings]'[0m
  [1m[35m (0.0ms)[0m  EXEC sp_executesql N'SELECT MAX([cms_menus].[updated_at]) AS max_id FROM [cms_menus]'
  [1m[36mProject Load (0.0ms)[0m  [1mEXEC sp_executesql N'SELECT TOP (1) [projects].* FROM [projects] WHERE [projects].[identifier] = N''uco-cms'''[0m
  [1m[35mSQL (0.0ms)[0m  EXEC sp_executesql N'SELECT [enabled_modules].[name] FROM [enabled_modules] WHERE [enabled_modules].[project_id] = 10'
  [1m[36mActsAsTaggableOn::Tag Load (15.6ms)[0m  [1mEXEC sp_executesql N'SELECT [tags].* FROM [tags] INNER JOIN [taggings] ON [tags].[id] = [taggings].[tag_id] WHERE [taggings].[taggable_id] IS NULL AND [taggings].[taggable_type] = N''KbArticle'' AND (taggings.context = N''tags'' AND taggings.tagger_id IS NULL)'[0m
Completed 500 Internal Server Error in 31.2ms

NoMethodError (undefined method `author_id=' for #<KbArticle:0x34e8430>):
  GEM_HOME/gems/activemodel-3.2.21/lib/active_model/attribute_methods.rb:407:in `method_missing'
  GEM_HOME/gems/activerecord-3.2.21/lib/active_record/attribute_methods.rb:149:in `method_missing'
  plugins/redmine_knowledgebase/app/controllers/articles_controller.rb:55:in `create'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:513:in `_run__528266281__process_action__672185047__callbacks'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  GEM_HOME/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  GEM_HOME/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  GEM_HOME/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  GEM_HOME/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
  GEM_HOME/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  GEM_HOME/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  GEM_HOME/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  GEM_HOME/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  GEM_HOME/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  GEM_HOME/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  GEM_HOME/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  GEM_HOME/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__293038908__call__10180633__callbacks'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  GEM_HOME/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  GEM_HOME/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  GEM_HOME/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  GEM_HOME/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  GEM_HOME/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  GEM_HOME/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  GEM_HOME/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  GEM_HOME/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  GEM_HOME/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
  GEM_HOME/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/lint.rb:48:in `_call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/lint.rb:36:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
  GEM_HOME/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
  C:/Zoo/Workers/ruby/lib/app.rb:65:in `call'
  C:/Zoo/Workers/ruby/lib/request.rb:54:in `serve'
  C:/Zoo/Workers/ruby/lib/worker.rb:42:in `handle_request'
  C:/Zoo/Workers/ruby/lib/worker.rb:36:in `process'
  C:/Zoo/Workers/ruby/lib/worker.rb:20:in `block in run'
  C:/Zoo/Workers/ruby/lib/worker.rb:20:in `loop'
  C:/Zoo/Workers/ruby/lib/worker.rb:20:in `run'
  C:/Zoo/Workers/ruby/zoorack.rb:30:in `<module:Zack>'
  C:/Zoo/Workers/ruby/zoorack.rb:12:in `<main>'
```
```
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [i386-mingw32]
  Rails version                  3.2.21
  Environment                    development
  Database adapter               SQLServer
```

**Comment by alexbevi** [comment]
Just curious if this is still an issue

From what i can see at http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Ruby-interpreter, There are issues on Windows, as well as with the SqlServer adapter, so I'm not sure if this is my bug, or a general issue ...

**Comment by alexbevi** [comment]
@andreydruz, closing this for now as I haven't heard back in a while. If the issue persists and you can provide more info, please re-open the ticket.
