### ISSUE TITLE
Plugin is impossible to install

### ISSUE THREAD

**Issue by lchojnowski** [alexbevi/redmine_knowledgebase#298]

**Comment by lchojnowski** [comment]
I get the following error during installation:

```
rake redmine:plugins:migrate NAME=redmine_knowledgebase
Migrating redmine_knowledgebase (Knowledgebase)...
== 20121205100143 AddVersioning: migrating ====================================
-- add_column(:kb_articles, :version_comments, :string, {:limit=>255, :default=>""})
   -> 0.0106s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Unknown key: :include. Valid keys are: :columns, :project_key, :date_column, :permission, :scope, :preload/Users/lchojnowski/Code/redror/lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:37:in `acts_as_searchable'
/Users/lchojnowski/Code/redror/plugins/redmine_knowledgebase/app/models/kb_article.rb:28:in `<class:KbArticle>'
/Users/lchojnowski/Code/redror/plugins/redmine_knowledgebase/app/models/kb_article.rb:5:in `<top (required)>'
/Users/lchojnowski/Code/redror/plugins/redmine_knowledgebase/db/migrate/20121205100143_add_versioning.rb:4:in `up'
/Users/lchojnowski/Code/redror/lib/redmine/plugin.rb:481:in `migrate_plugin'
/Users/lchojnowski/Code/redror/lib/redmine/plugin.rb:453:in `migrate'
/Users/lchojnowski/Code/redror/lib/redmine/plugin.rb:464:in `migrate'
/Users/lchojnowski/Code/redror/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by alexbevi** [comment]
@lchojnowski the plugin hasn't been maintained in a bit .... I'm hoping to rectify that soon.

Note that you should try the `redmine-3.0-compat` branch if you're installing against a redmine 3.x instance

**Comment by alexbevi** [comment]
Just pushed out 3.1.0. try that and let me know ;)

**Comment by allustin** [comment]
latest master, same error

```
/home/redmine/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
RedmineActsAsTaggableOn::Migration::SchemaMismatchError: A plugin is already using the "tags" or "taggings" tables, and
the structure of the table does not match the structure expected
by redmine_knowledgebase.
```

simple steps for reproduce

install redmine via docker-compose

```
wget https://raw.githubusercontent.com/sameersbn/docker-redmine/master/docker-compose.yml
docker-compose up -d
```

install plugin into container - RAILS_ENV auto sets to production by docker container maintainer

```
docker exec -it redmine_redmine_1 git clone git://github.com/alexbevi/redmine_knowledgebase.git plugins/redmine_knowledgebase
```

bundle update

```
 docker exec -it redmine_redmine_1 bundle update
```

and finaly migrate plugin first time 

```
docker exec -it redmine_redmine_1 bundle exec rake redmine:plugins:migrate NAME=redmine_knowledgebase
```
there is a timeout on act_as_taggable migration and script are stoped without exception

when if i try migrate or downgrade and migrate i've got an error

```
sudo docker exec -it redmine_redmine_1 bundle exec rake redmine:plugins:migrate NAME=redmine_knowledgebase
Migrating redmine_knowledgebase (Knowledgebase)...
== 20100210212009 CreateCategories: migrating =================================
-- create_table(:kb_categories)
   -> 0.2800s
== 20100210212009 CreateCategories: migrated (0.2802s) ========================

== 20100211210218 AddParentIdToCategories: migrating ==========================
-- add_column(:kb_categories, :parent_id, :int)
   -> 0.0021s
== 20100211210218 AddParentIdToCategories: migrated (0.0031s) =================

== 20100211212704 CreateArticles: migrating ===================================
-- create_table(:kb_articles)
   -> 0.3373s
== 20100211212704 CreateArticles: migrated (0.3380s) ==========================

== 20100213145708 AddAuthorToArticle: migrating ===============================
-- add_column(:kb_articles, :author_id, :int, {:default=>0, :null=>false})
   -> 0.1003s
== 20100213145708 AddAuthorToArticle: migrated (0.1010s) ======================

== 20100213201848 AddViewingTables: migrating =================================
== 20100213201848 AddViewingTables: migrated (0.3470s) ========================

== 20100216000133 AddNestedSetBoundriesToCategory: migrating ==================
-- add_column(:kb_categories, :lft, :int)
   -> 0.0011s
-- add_column(:kb_categories, :rgt, :int)
   -> 0.0008s
== 20100216000133 AddNestedSetBoundriesToCategory: migrated (0.0023s) =========

== 20100317201659 AddRatingsToArticles: migrating =============================
== 20100317201659 AddRatingsToArticles: migrated (1.4483s) ====================

== 20100329103527 AddCommentsCountToArticles: migrating =======================
-- add_column(:kb_articles, :comments_count, :int)
   -> 0.0011s
== 20100329103527 AddCommentsCountToArticles: migrated (0.0013s) ==============

== 20110131145123 AddProjectIdToArticles: migrating ===========================
-- add_column(:kb_articles, :project_id, :int, {:default=>0})
   -> 0.1639s
== 20110131145123 AddProjectIdToArticles: migrated (0.1641s) ==================

== 20121005075010 AddUpdaterToArticle: migrating ==============================
-- add_column(:kb_articles, :updater_id, :int, {:default=>0, :null=>false})
   -> 0.3214s
== 20121005075010 AddUpdaterToArticle: migrated (0.3219s) =====================

== 20121030102100 AddProjectIdToCategories: migrating =========================
-- add_column(:kb_categories, :project_id, :int, {:default=>0})
   -> 0.3529s
== 20121030102100 AddProjectIdToCategories: migrated (0.3532s) ================

== 20121205100143 AddVersioning: migrating ====================================
-- add_column(:kb_articles, :version_comments, :string, {:limit=>255, :default=>""})
   -> 0.1483s
-- add_index("kb_article_versions", :kb_article_id, {:name=>:kb_article_versions_kbaid})
   -> 0.1230s
-- add_index("kb_article_versions", :updated_at, {:name=>:index_kb_article_versions_on_updated_at})
   -> 0.1021s
== 20121205100143 AddVersioning: migrated (1.7818s) ===========================

== 20130513154700 AddTagsAndTaggings: migrating ===============================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

A plugin is already using the "tags" or "taggings" tables, and
the structure of the table does not match the structure expected
by redmine_knowledgebase.
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bundler/gems/redmine_acts_as_taggable_on-a939baeb9fe2/lib/redmine_acts_as_taggable_on/migration.rb:76:in `assert_schema_match!'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bundler/gems/redmine_acts_as_taggable_on-a939baeb9fe2/lib/redmine_acts_as_taggable_on/migration.rb:64:in `ok_to_go_up?'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bundler/gems/redmine_acts_as_taggable_on-a939baeb9fe2/lib/redmine_acts_as_taggable_on/migration.rb:15:in `up'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in `exec_migration'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:464:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
RedmineActsAsTaggableOn::Migration::SchemaMismatchError: A plugin is already using the "tags" or "taggings" tables, and
the structure of the table does not match the structure expected
by redmine_knowledgebase.


```

enviroment is

```
./bin/about
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.6.4
  Filesystem
Redmine plugins:
  redmine_knowledgebase          3.1.0
```

**Comment by alexbevi** [comment]
I hate redmine + tags :|

Thanks @allustin. I'm most likely going to have to rewrite the tagging integration (though I'd be happier to just drop it completely at this point ..)

**Comment by thinknot** [comment]
Yeah wow who knew Redmine+tags == evil dependency hell.
I recently started playing around with the RedmineCRM suite of plugins; watch out if you rollback their contacts migrations, the tagging tables used by redmine_knowledgebase get dropped. :)
