### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Hax0rG1rl** [alexbevi/redmine_knowledgebase#373]
Hi, 

**[Description]**

**Env:** Redmine 4.1.1-1, Bitnami VM, GCP. 

Current software versions: 

Operating system: Debian (9)

Installed software: 

- Ghostscript (9.05)
- Git (2.26.1)
- Apache (2.4.43)
- ImageMagick (6.9.8)
- lego (3.5.0)
- MySQL (5.7.29)
- OpenSSL (1.1.1g)
- Perl (5.16.3)
- PHP (7.3.16)
- phpMyAdmin (5.0.2)
- Redmine (4.1.1)
- Ruby (2.5.8)
- SQLite (3.31.1)
- Subversion (1.13.0)

**netstat -na |  grep tcp** output

```
tcp        0      0 0.0.0.0:3690            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:41239         0.0.0.0:*               LISTEN     
[...]
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::443                  :::*                    LISTEN 
```

Local Mysql config:

```
# Default setup is given for MySQL 5.7.7 or later.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).
production:
  adapter: mysql2
  database: bitnami_redmine
  host: localhost
  username: [_username_] 
  password: [_my_secret_password_]
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
  socket: /opt/bitnami/mysql/tmp/mysql.sock
```

Plugin package used: https://github.com/reshetov/redmine_knowledgebase 

Followed the install steps/hints from the official documentation and from here: 

https://docs.bitnami.com/installer/apps/redmine/configuration/install-plugins/

**Issue:** 

I am getting the following error message"

```
sudo rake redmine:plugins:migrate NAME:redmine_knowledgebase --trace
(in /opt/bitnami/apps/redmine/htdocs)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
rake aborted!
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:90:in `connection'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:550:in `get_all_versions'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:558:in `current_version'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:540:in `migrate_plugin'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:497:in `block in migrate'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:496:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:496:in `migrate'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

It seems it cannot open a sock connection to the MySQL instance that is odd as long the instance is up, healthy, and running. 

Any ideas on how can I resolve this? 

Thanks!

**Comment by Hax0rG1rl** [comment]
**[Updates]** 

Right. So, I sued a post from a while ago and got a symbolic link. 

```
sudo ln -s /opt/bitnami/mysql/tmp/mysql.sock /tmp/mysql.sock
```

However, now got this: 

```
** Execute environment
** Execute redmine:plugins:migrate
rake aborted!
Mysql2::Error::ConnectionError: Access denied for user 'root'@'localhost' (using password: NO)
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
/opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
```

**Comment by robspearman** [comment]
Redmine 4.1 support was merged in today.
