### ISSUE TITLE
Database migration failed at 20150326093122_add_taggings_counter_cache_to_tags.rb

### ISSUE THREAD

**Issue by ace280** [alexbevi/redmine_knowledgebase#382]
When running the database migration ( rake redmine:plugins:migrate NAME=redmine_knowledgebase) I ran into an error:

rake aborted!
SyntaxError: D:/redmine-4.1.1_B/plugins/redmine_knowledgebase/db/migrate/20150326093122_add_taggings_counter_cache_to_ta
gs.rb:6: syntax error, unexpected keyword_rescue, expecting keyword_end
    rescue
          ^
D:/redmine-4.1.1_B/lib/redmine/plugin.rb:510:in `up'
D:/redmine-4.1.1_B/lib/redmine/plugin.rb:542:in `migrate_plugin'
D:/redmine-4.1.1_B/lib/redmine/plugin.rb:483:in `migrate'
D:/redmine-4.1.1_B/lib/redmine/plugin.rb:494:in `migrate'
D:/redmine-4.1.1_B/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate

My workaround was to remove the rescue call in question. Rake was able to finish the migration and the plugin seems to work now. I will keep you updated if I run into any other problems.

![grafik](https://user-images.githubusercontent.com/25365744/93090912-b9756b80-f69d-11ea-8a12-8c7deeb96dd0.png)

**Comment by ace280** [comment]
I am not good enough at doing Ruby to know if the Ruby version has something to do with this error, but it is one of hot scents.
