### ISSUE TITLE
PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous 

### ISSUE THREAD

**Issue by iwasi-1234** [alexbevi/redmine_knowledgebase#392]
### Environment
* OS: CentOS 7.9
* Redmine: 4.1 (Migrate from Redmine 3.4.13)
* Ruby: 2.6.2p47
* DB: PostgreSQL 9.6.19
* Knowledgebase Plugins: 4.1.1
* Other Plugins: 
    * Redmine Custom   Auto-Complete plugin: 0.0.1
    * Redmine Export With Journals   plugin: 0.1.0
    * Redmine Issue Templates plugin: 1.1.0
    * Redmine Issues Panel plugin: 0.0.1
    * Redmine Issues Summary Graph plugin: 0.0.10
    * Redmine persist wiki format  plugin: 2.0.1
    * Redmine - Smile - Hide / Show Sidebar: 1.0.7
    * Redmine Theme Changer plugin: 0.4.0
    * Redmine Watcher Filter  plugin: 4.0.0-alpha
    * Redmine Wiki Extensions plugin: 0.9.2
    * Selectbox Autocompleter plugin: 1.2.１
    * View Customize plugin: 2.8.0

### Description

I migrated from redmine 3.4.13 to redmine 4.1.
I could create KB article and show the article on "overview"/"content". But I couldn't  refer to tag link, and displayed "Internal error" message:
![knowlegdebase_overview](https://user-images.githubusercontent.com/76514641/102983732-de586500-454f-11eb-92c1-89ffe36035f4.png)
```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back
```
 And following message were confirmed in production.log:
```
  KbArticle Load (1.5ms)  SELECT DISTINCT kb_articles.*  FROM "kb_articles" INNER JOIN taggings kb_articles_taggings ON kb_articles_taggings.taggable_id = kb_articles.id AND kb_articles_taggings.taggable_type = 'KbArticle' INNER JOIN tags kb_articles_tags ON kb_articles_tags.id = kb_articles_taggings.tag_id WHERE "kb_articles"."project_id" = $1 AND ((kb_articles_tags.name LIKE 'tagtest')) ORDER BY title asc  [["project_id", 33]]
  RedmineCrm::ActsAsTaggable::Tag Load (0.5ms)  SELECT tags.id, tags.name, COUNT(*) AS count FROM "tags" INNER JOIN taggings ON tags.id = taggings.tag_id INNER JOIN kb_articles ON kb_articles.id = taggings.taggable_id WHERE ("id" = 181 AND taggings.taggable_type = 'KbArticle') GROUP BY tags.id, tags.name HAVING (COUNT(*) > 0)
Completed 500 Internal Server Error in 29ms (ActiveRecord: 12.4ms)
  
ActiveRecord::StatementInvalid (PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous
LINE 1: ...s ON kb_articles.id = taggings.taggable_id WHERE ("id" = 181...
                                                             ^
: SELECT tags.id, tags.name, COUNT(*) AS count FROM "tags" INNER JOIN taggings ON tags.id = taggings.tag_id INNER JOIN kb_articles ON kb_articles.id = taggings.taggable_id WHERE ("id" = 181 AND taggings.taggable_type = 'KbArticle') GROUP BY tags.id, tags.name HAVING (COUNT(*) > 0)):
  
plugins/redmine_knowledgebase/app/controllers/categories_controller.rb:133:in `sort'
plugins/redmine_knowledgebase/app/controllers/categories_controller.rb:133:in `prepare'
plugins/redmine_knowledgebase/app/controllers/categories_controller.rb:20:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```
`tagtest` is sample tag.

Is any workaround of this issue?

Regards,

**Comment by kay54068** [comment]
I have the same issue
